-- DELETE FROM CITY;
-- ALTER TABLE FOUNDER_METER = 1;
INSERT INTO FOUNDER_METER (LINKEDIN_LINK, AUTH_METER, ADMIN_COMMENT, ADDED_DATE) VALUES ('/li/sergey', 1, 'Does not do anything but hype', NOW());
