DROP TABLE IF EXISTS FOUNDER_METER;
CREATE TABLE FOUNDER_METER (
	ID INT PRIMARY KEY AUTO_INCREMENT,
	NAME VARCHAR(50),
	LINKEDIN_LINK VARCHAR(300) UNIQUE,
	AUTH_METER INT,
	ADMIN_COMMENT TEXT,
	ADDED_DATE DATETIME,
	UPDATED_DATE DATETIME
);